version: '3.8'

services:
  postgres:
    image: postgres:12.4-alpine
    container_name: SimpleShop
    restart: always
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=123qwe
        - POSTGRES_DB=SimpleShop
        - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - ./docker/db:/var/lib/postgresql/data/pgdata